<!DOCTYPE html>
<HTML>
<HEAD>
    <TITLE> Add/Remove dynamic rows in HTML table </TITLE>
    <SCRIPT >

     // document.getElementById('gridTable').rows[RowNumber].deleteCell(CellNumberInRow); 
     
        function addRow(tableID) {
 
            var table = document.getElementById(tableID);
 
            var rowCount = table.rows.length;
            var newId=0;
            for (var h=0;h<rowCount; h++ ) {
				if (parseInt(table.rows[h].cells[1].childNodes[0].nodeValue)>=parseInt(newId)) {
					newId=(parseInt(table.rows[h].cells[1].childNodes[0].nodeValue)+1).toString();
				}
            }
            var row = table.insertRow(rowCount);
 
            var colCount = table.rows[0].cells.length;

            
            for(var i=0; i<colCount; i++) {
 
                var newcell = row.insertCell(i);
                if (i==0) {
                	newcell.innerHTML='<INPUT type="checkbox" name="chk"/>';
                	newcell.childNodes[0].checked = false;
                }
                else if (i==1) {
                	newcell.innerHTML=newId;
                }
                else {
                newcell.innerHTML = table.rows[0].cells[i].innerHTML;
                //alert(newcell.childNodes);
                switch(newcell.childNodes[0].type) {
                    case "text":
                            newcell.childNodes[0].value = "";                            
                            break;
                    case "checkbox":
                            newcell.childNodes[0].checked = false;
                            break;
                    case "select-one":
                            newcell.childNodes[0].selectedIndex = 0;
                            break;
                }
              }

            }
        }
 
        function deleteRow(tableID) {
            try {
            var table = document.getElementById(tableID);
            var rowCount = table.rows.length;
 
            for(var i=0; i<rowCount; i++) {
                var row = table.rows[i];
                var chkbox = row.cells[0].childNodes[0];
                if(null != chkbox && true == chkbox.checked) {
                    if(rowCount <= 1) {
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
 
 
            }
            }catch(e) {
                alert(e);
            }
        }
 
    </SCRIPT>
</HEAD>
<BODY>
 
    <INPUT type="button" value="Add Row" onclick="addRow('dataTable')" />
 
    <INPUT type="button" value="Delete Row" onclick="deleteRow('dataTable')" />
 
    <TABLE id="dataTable" width="350px" border="1">
        <TR>
            <TD></TD>
            <TD>5</TD>
            <TD><INPUT type="text" name="txt"/></TD>
            <TD>
                <SELECT name="country">
                    <OPTION value="in">India</OPTION>
                    <OPTION value="de">Germany</OPTION>
                    <OPTION value="fr">France</OPTION>
                    <OPTION value="us">United States</OPTION>
                    <OPTION value="ch">Switzerland</OPTION>
                </SELECT>
            </TD>
        </TR>
    </TABLE>
 
</BODY>
</HTML>
